version: 18
jobs:
- name: git-sync-to-github
  steps:
  - !PushRepository
    name: push-to-github
    remoteUrl: https://github.com/archlinux365/9318-archlinux-docker.git
    userName: gnuhub
    passwordSecret: github-token
    withLfs: false
    force: false
    condition: ALWAYS
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
