name: docker build

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v3
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}
      - run: |
          env
          docker build . -t ghcr.io/${GITHUB_REPOSITORY}/$GITHUB_REF_NAME:$GITHUB_RUN_NUMBER -t ghcr.io/${GITHUB_REPOSITORY}/$GITHUB_REF_NAME:latest
          docker push ghcr.io/${GITHUB_REPOSITORY}/$GITHUB_REF_NAME:$GITHUB_RUN_NUMBER
          docker push ghcr.io/${GITHUB_REPOSITORY}/$GITHUB_REF_NAME:latest
