name: docker build

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v3
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}
      - run: |
          env
          # docker build . -t ghcr.io/${{ github.actor }}/${{ secrets.image }}:apricot
          # docker push ghcr.io/${{ github.actor }}/${{ secrets.image }}:apricot
