name: docker build

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v3
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: build docker
        run: |
          env
          docker build . -f Dockerfile.$GITHUB_REF_NAME -t ghcr.io/${GITHUB_REPOSITORY}/$GITHUB_REF_NAME:$GITHUB_RUN_NUMBER -t ghcr.io/${GITHUB_REPOSITORY}/$GITHUB_REF_NAME:latest
          docker push ghcr.io/${GITHUB_REPOSITORY}/$GITHUB_REF_NAME:$GITHUB_RUN_NUMBER
          docker push ghcr.io/${GITHUB_REPOSITORY}/$GITHUB_REF_NAME:latest
          docker run ghcr.io/${GITHUB_REPOSITORY}/$GITHUB_REF_NAME:$GITHUB_RUN_NUMBER pacman -Sl > release.$GITHUB_RUN_NUMBER.packages.list.all.txt
          docker run ghcr.io/${GITHUB_REPOSITORY}/$GITHUB_REF_NAME:$GITHUB_RUN_NUMBER pacman -Qe > release.$GITHUB_RUN_NUMBER.packages.list.installed.txt
      - name: Get build_no
        id: build_no
        run: echo "::set-output name=build_no::$GITHUB_REF_NAME-$GITHUB_RUN_NUMBER"
  
      - name: get docker tag
        id: dockertag
        run: echo "::set-output name=body::$(date) Please check release.$GITHUB_RUN_NUMBER.packages.list.all.txt and release.$GITHUB_RUN_NUMBER.packages.list.installed.txt `docker pull ghcr.io/archlinux365/9318-archlinux-docker/$GITHUB_REF_NAME:$GITHUB_RUN_NUMBER`"
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.build_no.outputs.build_no }}
          name: ${{ steps.build_no.outputs.build_no }}
          body: ${{steps.dockertag.outputs.body}}
          draft: false
          prerelease: false
          files: |
           release.*.txt
